export const SOUTH_AFRICAN_CITIES = [
  "Bloemfontein",
  "Cape Town",
  "Centurion",
  "Durban",
  "East London",
  "Emalahleni (Witbank)",
  "George",
  "Gqeberha (Port Elizabeth)",
  "Johannesburg",
  "Kimberley",
  "Mahikeng",
  "Mbombela (Nelspruit)",
  "Mthatha",
  "Polokwane",
  "Paarl",
  "Pretoria",
  "Richards Bay",
  "Rustenburg",
  "Soweto",
  "Stellenbosch",
  "Thohoyandou",
  "Upington",
  "Welkom",
] as const;
